name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake
        uses: mishmanners/MishManners-GitHub-Actions@main
        with:
          github_user_name: kkrishhhh
          snake_head_color: "#818CF8"
          background_color: "#0d1117"
          dot_color_empty: "#161b22"
          dot_color_1: "#312e81"
          dot_color_2: "#4338ca"
          dot_color_3: "#6366f1"
          dot_color_4: "#818cf8"

      - name: Push output
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
